#+title: Cosine Similarity

Cosine similarity is one way to measure the similarity between two vectors.
It's defined as the cosine of the angle formed by the vectors.

This means vectors with small angle difference will have a cosine closer to 1.0
("100%"), while vectors with large angle difference will have a cosine closer to
0.0 ("0%").

Note: cosine similary just takes into account the angle, not the magnitude of
the vector, so it may not be suitable for every comparison.

Here is how you can compute the cosine similarity of two vectors \(\vec{A}\) and \(\vec{B}\):

\begin{equation}
\text{Cosine Similarity} =
\frac{{\vec {A}} \cdot {\vec {B}}}
     {\|{\vec {A}}\|_{2}\|{\vec {B}}\|_{2}}
\end{equation}

Cosine similarity is commonly used for comparing text similarity.
The idea is to take the sentences that you want to compare and convert each into
a vector representing its meaning in a process called embedding.

The cool thing about cosine similarity is that it works regardless of how many
dimensions your vector has.
GPT 4o embeddings, for example, consist of vectors with 1536 dimensions.

# {\displaystyle sim_{cos}({\vec {x}},{\vec {y}})=
# {\frac {{\vec {x}}\cdot {\vec {y}}}
# {\|{\vec {x}}\|_{2}\|{\vec {y}}\|_{2}}}} 

# \begin{equation}
# \text{Cosine Similarity} =
# \frac{\sum_{i=1}^{n} A_i B_i}
# {\sqrt{\sum_{i=1}^{n} A_i^2} \sqrt{\sum_{i=1}^{n} B_i^2}}
# \end{equation}

# Given the phrases:
# 1. "love you"
# 2. "you love"
# 3. "love love"
# 4. "you"

# We can represent them as:
# | love | you | angle |
# |------+-----+-------|
# |    1 |   1 |    45 |
# |    1 |   1 |    45 |
# |    2 |   0 |     0 |
# |    0 |   1 |    90 |

# If we compare first and second phrases, the angle between them is 0, and cos 0
# is 1, so the cosine similarity is 1.

# If we compare first and third phrases, the angle between them is 45, and cos 45
# is 0.71.

# If we compare second and forth phrases, the angle between them is also 45, so
# 0.71.

# If we compare third and forth, their angle is 90, and cos 90 is 0.
# Make sense since there is no similar word between the phrases.
